name: CI & Release

on:
  push:
    branches: [ "main" ]
    tags:     [ "v*" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  lint_and_test:
    name: Lint & Test (Go)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.x'
          cache: true

      - name: go fmt (check)
        run: |
          CHANGED=$(gofmt -l .)
          if [ -n "$CHANGED" ]; then
            echo "These files are not gofmt-ed:"
            echo "$CHANGED"
            echo "Run: go fmt ./..."
            exit 1
          fi

      - name: go vet
        run: go vet ./...

      - name: Run tests
        run: go test ./... -v

  release_dockerhub:
    name: Release to Docker Hub on tag
    runs-on: ubuntu-latest
    needs: lint_and_test
    if: startsWith(github.ref, 'refs/tags/')  # только при пуше тега

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/parcel-tracker
          tags: |
            type=ref,event=tag        # v1.2.3
            type=raw,value=latest     # параллельно latest

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}